version: '2'
services:
  punchgate:
    image: nginx
    volumes:
      - ./nginx/nginx-template.conf:/nginx-template.conf
      - ./nginx/.htpasswd:/.htpasswd
      - ./public:/usr/share/nginx/html
      - ./cert:/etc/ssl/certs/
    environment:
      - PROTECTED_HOST=punchapi
      - PROTECTED_HOST_PORT=8080
    ports:
      - 8443:443
    links:
      - punchapi
    command: /bin/bash -c "envsubst < /nginx-template.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  punchapi:
    image: python:3.6
    ports:
      - 8080:8080
    environment:
      - FLASK_DEBUG=1
      - SERVER_PORT=8080
      - MONGO_HOST=punchdb:27017
      - PYTHONPATH=$PYTHONPATH:/usr/src/
    volumes:
      - ./requirements.txt:/requirements.txt
      - ./server:/usr/src/server
    command: bash -c "pip install -r /requirements.txt && cd /usr/src/ && python server/main.py"
    links:
      - punchdb
  punchdb:
    image: mongo
    ports:
      - 27017:27017

